// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpq-7q8cIWB6N1rvV-Hu-oUdLAlejtYjU',
    appId: '1:23042009868:web:34f78732e5ea80841fb729',
    messagingSenderId: '23042009868',
    projectId: 'timeboxing-aljabar',
    authDomain: 'timeboxing-aljabar.firebaseapp.com',
    storageBucket: 'timeboxing-aljabar.appspot.com',
    measurementId: 'G-CY0QCV1DML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARMSOfqIQ-mvu2pjtEMJDdeVyTDM3uVY0',
    appId: '1:23042009868:android:ee40c666b3ee034c1fb729',
    messagingSenderId: '23042009868',
    projectId: 'timeboxing-aljabar',
    storageBucket: 'timeboxing-aljabar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgU9vhE2bU_WyLbFbCG75tyAGixXxXibI',
    appId: '1:23042009868:ios:47bcb2963e426bdc1fb729',
    messagingSenderId: '23042009868',
    projectId: 'timeboxing-aljabar',
    storageBucket: 'timeboxing-aljabar.appspot.com',
    iosClientId:
        '23042009868-8nl9k9saeiv96p0i5a5sgbcjh8qj021q.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeboxing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgU9vhE2bU_WyLbFbCG75tyAGixXxXibI',
    appId: '1:23042009868:ios:c5a226fcb1ecd6d21fb729',
    messagingSenderId: '23042009868',
    projectId: 'timeboxing-aljabar',
    storageBucket: 'timeboxing-aljabar.appspot.com',
    iosClientId:
        '23042009868-6h9ab9rk40pg4d46p2sbleajofj1p3b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeboxing.RunnerTests',
  );
}
